adding exception handling
saltastroops/salt-api-old pull request #19
Opened 2020-12-07 12:23 UTC by Lonwabo11

2020-12-07 15:26 UTC, hettlage requested changes
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/19)* status: all files reviewed, 30 unresolved discussions (waiting on @Lonwabo11)

___
*[saltapi/auth/authorization.py, line 19 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxhJR33n6OroBe06kg:-MNxhJR33n6OroBe06kh:bafive3) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/authorization.py#L19)):*
> ```Python
> from saltapi.repository.user_repository import User, is_user_pc, is_user_pi
> 
> info_log = setup_logging(
> ```

You probably should use

```
logger = logging.getLogger(__name__)
```
___
*[saltapi/auth/authorization.py, line 44 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxh_nw6E0NjW5Qt6BE:-MNxh_nxDEv8svxcq5st:bg19zp8) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/authorization.py#L44)):*
> ```Python
>             if _name == name:
>                 return member
>         info_log.info(msg=f"Unknown permission detected from: {name}")
> ```

Why don't you just say "Unknown permission: {name}"? :-)

This should be an error rather than info.
___
*[saltapi/auth/authorization.py, line 59 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxhySE7ocxara_t-oF:-MNxhySE7ocxara_t-oG:bfulppx) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/authorization.py#L59)):*
> ```Python
>             if _name == name:
>                 return member
>         info_log.info(msg=f"Unknown role detected for {name}")
> ```

Why don't you just say "Unknown role: {name}"? :-)

This should be an error rather than info.
___
*[saltapi/auth/authorization.py, line 102 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxiPy2EGBpfsZzfSvt:-MNxiPy2EGBpfsZzfSvu:b-45bp2q) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/authorization.py#L102)):*
> ```Python
>         authorization_header = request.headers["Authorization"]
>         if not authorization_header.startswith("Bearer "):
>             error_log.error(msg=f"Invalid Authorization header value. The header value must have the format Bearer")
> ```

As this is a user error, I'd rather use info and say something like "Invalid authorization header sent by user.".
___
*[saltapi/auth/authorization.py, line 113 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxiiqD2Iwz5qjdSg8Q:-MNxiiqD2Iwz5qjdSg8R:b-6wxq3b) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/authorization.py#L113)):*
> ```Python
>         except Exception:
>             exc_type, value, traceback = sys.exc_info()
>             error_log.error(msg=f"failed with exception{exc_type.__name__}. Invalid or expired authentication token.")
> ```

I'm not sure the exception type needs logging. But if you want to log it, you might consider logging the stack trace.
___
*[saltapi/auth/authorization.py, line 119 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxjFaHC7ExWkwypfGk:-MNxjFaHC7ExWkwypfGl:b-n8kjlf) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/authorization.py#L119)):*
> ```Python
> 
>         if not user:
>             error_log.error(msg=f"No user id was found for {user}")
> ```

"No user found for id {payload.iuser_id}."
___
*[saltapi/auth/token.py, line 16 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxjRWQBwPKK02iQcmS:-MNxjRWQBwPKK02iQcmT:b-v8j0qu) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/token.py#L16)):*
> ```Python
> 
> 
> info_log = setup_logging(
> ```

Duplicate code. Also see comments for authorization.py.
___
*[saltapi/auth/token.py, line 57 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxnA6d3QHKxAQXJyiC:-MNxnA6d3QHKxAQXJyiD:b-3m6bot) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/token.py#L57)):*
> ```Python
>             key = f.read()
>     else:
>         info_log.info(msg=f"Unsupported algorithm: {algorithm}")
> ```

This should be an error rather than info.
___
*[saltapi/auth/token.py, line 76 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxnGZx47dl2FDmKPZp:-MNxnGZx47dl2FDmKPZq:b-3m6bot) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/token.py#L76)):*
> ```Python
>             key = f.read()
>     else:
>         info_log.info(msg=f"Unsupported algorithm: {algorithm}")
> ```

This should be an error rather than info.
___
*[saltapi/auth/token.py, line 82 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxnJVW0zw8rnt0yUdW:-MNxnJVW0zw8rnt0yUdX:bk1qps7) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/token.py#L82)):*
> ```Python
>         return TokenPayload(user_id=payload["user_id"], roles=payload.get("roles", []))
>     except jwt.ExpiredSignatureError:
>         error_log.error(msg=f"The authentication token has expired for {TokenPayload.user_id}")
> ```

I'm not convinced this should be logged. If you log it, it probably should be info or warning, as it is a user error.
___
*[saltapi/auth/token.py, line 86 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxn_8jDS48lekGe_wz:-MNxn_8jDS48lekGe_x-:b-n1a0tj) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/token.py#L86)):*
> ```Python
>     except Exception:
>         exc_type, value, traceback = sys.exc_info()
>         error_log.error(msg=f"Failed with exception {exc_type.__name__}."
> ```

Rather log the stack trace. But I'm not convinced it needs to be logged.
___
*[saltapi/graphql/directives.py, line 18 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxjkWrApeigmVh9wE0:-MNxjkWrApeigmVh9wE1:b-v8j0qu) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/graphql/directives.py#L18)):*
> ```Python
> from saltapi.repository.logging_errors import setup_logging
> 
> error_log = setup_logging(
> ```

Duplicate code. Also see comments for authorization.py.
___
*[saltapi/graphql/directives.py, line 49 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxjyY3CKFA6q1O-TeY:-MNxjyY3CKFA6q1O-TeZ:b-gk5oov) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/graphql/directives.py#L49)):*
> ```Python
>             ):
>                 exc_type, value, traceback = sys.exc_info()
>                 error_log.error(msg=f"Failed with exception {exc_type.__name__}. "
> ```

You haven't failed with any exception here.

Also, this is a user error, and as such info might be more appropriate.

And this file has changed...
___
*[saltapi/graphql/scalars.py, line 8 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxkUYa4xW6dj6PqUml:-MNxkUYa4xW6dj6PqUmm:b-v8j0qu) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/graphql/scalars.py#L8)):*
> ```Python
> import logging
> from saltapi.repository.logging_errors import setup_logging
> ```

Duplicate code. Also see comments for authorization.py.
___
*[saltapi/graphql/scalars.py, line 29 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxkX-mBwmWhRRbfizc:-MNxkX-mBwmWhRRbfizd:bqrpmcc) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/graphql/scalars.py#L29)):*
> ```Python
>     """Parse a proposal code value."""
>     if not proposal_code.startswith("2"):
>         error_log.error(msg=f"Invalid proposal code")
> ```

A user error. Use info [...]

2020-12-09 09:54 UTC, Lonwabo11 reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/19)* status: 1 of 8 files reviewed, 30 unresolved discussions (waiting on @hettlage)

___
*[saltapi/auth/authorization.py, line 19 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxhJR33n6OroBe06kg:-MO1ngbD2ExLzCoaFLtd:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/authorization.py#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You probably should use

```
logger = logging.getLogger(__name__)
```
</blockquote></details>

Done.
___
*[saltapi/auth/authorization.py, line 44 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxh_nw6E0NjW5Qt6BE:-MO1o1kr80uIoGnSIWZy:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/authorization.py#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why don't you just say "Unknown permission: {name}"? :-)

This should be an error rather than info.
</blockquote></details>

Done.
___
*[saltapi/auth/authorization.py, line 59 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxhySE7ocxara_t-oF:-MO1o0p14u8xEjPK-BRg:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/authorization.py#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why don't you just say "Unknown role: {name}"? :-)

This should be an error rather than info.
</blockquote></details>

Done.
___
*[saltapi/auth/authorization.py, line 102 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxiPy2EGBpfsZzfSvt:-MO1o6Jk2xPiro9k43f_:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/authorization.py#L102)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As this is a user error, I'd rather use info and say something like "Invalid authorization header sent by user.".
</blockquote></details>

Done.
___
*[saltapi/auth/authorization.py, line 113 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxiiqD2Iwz5qjdSg8Q:-MO1p-0k73cBulDsNHvD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/authorization.py#L113)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure the exception type needs logging. But if you want to log it, you might consider logging the stack trace.
</blockquote></details>

Done.
___
*[saltapi/auth/authorization.py, line 119 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxjFaHC7ExWkwypfGk:-MO1p8Uy-ULvyxqmthrR:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/authorization.py#L119)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"No user found for id {payload.iuser_id}."
</blockquote></details>

Done.
___
*[saltapi/auth/token.py, line 16 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxjRWQBwPKK02iQcmS:-MO1qeizAl2cSssTBTje:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/token.py#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Duplicate code. Also see comments for authorization.py.
</blockquote></details>

Done.
___
*[saltapi/auth/token.py, line 57 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxnA6d3QHKxAQXJyiC:-MO1qhnD-4TXZ-lRSFT4:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/token.py#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should be an error rather than info.
</blockquote></details>

Done.
___
*[saltapi/auth/token.py, line 76 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxnGZx47dl2FDmKPZp:-MO1qjmM-ZMJ5MkmRhDF:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/token.py#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should be an error rather than info.
</blockquote></details>

Done.
___
*[saltapi/auth/token.py, line 82 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxnJVW0zw8rnt0yUdW:-MO1qxlzAW8w3FwCharX:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/token.py#L82)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced this should be logged. If you log it, it probably should be info or warning, as it is a user error.
</blockquote></details>

Done.
___
*[saltapi/auth/token.py, line 86 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxn_8jDS48lekGe_wz:-MO1rIojDVS74WVIPfqf:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/auth/token.py#L86)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Rather log the stack trace. But I'm not convinced it needs to be logged.
</blockquote></details>

Done.
___
*[saltapi/graphql/directives.py, line 18 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxjkWrApeigmVh9wE0:-MO1sRunCk5ZCWqfxIDl:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/graphql/directives.py#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Duplicate code. Also see comments for authorization.py.
</blockquote></details>

Done.
___
*[saltapi/graphql/directives.py, line 49 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxjyY3CKFA6q1O-TeY:-MO5rRfsDTJcPTK9Oy2v:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/graphql/directives.py#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You haven't failed with any exception here.

Also, this is a user error, and as such info might be more appropriate.

And this file has changed...
</blockquote></details>

Done.
___
*[saltapi/graphql/scalars.py, line 8 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxkUYa4xW6dj6PqUml:-MO5rg2DCcppW4_-E0rF:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/graphql/scalars.py#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Duplicate code. Also see comments for authorization.py.
</blockquote></details>

Done.
___
*[saltapi/graphql/scalars.py, line 29 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxkX-mBwmWhRRbfizc:-MO1vej2EiAOv6Cjk4sD:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/graphql/scalars.py#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A user error. Use info instead.
</blockquote></details>

Done.
___
*[saltapi/graphql/scalars.py, line 41 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxkepI0lExSHdp5Aql:-MO1wLDv6Q9h616eGPDi:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/graphql/scalars.py#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is an error rather than info.
</blockquote></details>

Done.
___
*[saltapi/graphql/scalars.py, line 50 at r1](https://reviewable.io/reviews/saltastroops/salt-api/19#-MNxkk0MDgcVtAgP00hH:-MO5rqUb50KnDhIvyDQ7:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/df197a95d315d6ce555d55f964640d12ebb62de6/saltapi/graphql/scalars.py#L50)):*
<detai [...]

2020-12-14 08:38 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/19)* status: all files reviewed, 17 unresolved discussions (waiting on @hettlage and @Lonwabo11)

___
*[saltapi/auth/authorization.py, line 19 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVAzuQ73BQaw58zSQ0:-MOVAzuREk1Aik_YuXY_:b-nfn72g) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/auth/authorization.py#L19)):*
> ```Python
> 
> logger = logging.getLogger(__name__)
> logging.basicConfig(format="%(asctime)s [%(levelname)s]:[%(filename)s, line %(lineno)d]. %(message)s.",
> ```

Calling basicConfig again (without force=True) does nothing. You should call it once, at the very beginning of your app.
___
*[saltapi/auth/authorization.py, line 93 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVCAx6Cxi-_JylodyE:-MOVCAx6Cxi-_JylodyF:bngu45l) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/auth/authorization.py#L93)):*
> ```Python
>         authorization_header = request.headers["Authorization"]
>         if not authorization_header.startswith("Bearer "):
>             logging.basicConfig(level=logging.INFO)
> ```

This line (the basicConfig one) is unnecessary.
___
*[saltapi/auth/token.py, line 14 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVCpetAJZsTwGd7p9E:-MOVCpetAJZsTwGd7p9F:b-nfn72g) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/auth/token.py#L14)):*
> ```Python
> 
> logger = logging.getLogger(__name__)
> logging.basicConfig(format="%(asctime)s [%(levelname)s]:[%(filename)s, line %(lineno)d]. %(message)s.",
> ```

Calling basicConfig again (without force=True) does nothing. You should call it once, at the very beginning of your app.
___
*[saltapi/auth/token.py, line 71 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVD0go0IyBYtIThLv5:-MOVD0go0IyBYtIThLv6:bngu45l) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/auth/token.py#L71)):*
> ```Python
>         return TokenPayload(user_id=payload["user_id"], roles=payload.get("roles", []))
>     except jwt.ExpiredSignatureError:
>         logging.basicConfig(level=logging.INFO)
> ```

This line (the basicConfig one) is unnecessary.
___
*[saltapi/graphql/directives.py, line 43 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVELhD3rqK90zgTvMV:-MOVELhD3rqK90zgTvMW:bngu45l) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/graphql/directives.py#L43)):*
> ```Python
>                 user=user, auth=auth, roles=roles, permissions=permissions, **kwargs
>             ):
>                 logging.basicConfig(level=logging.INFO)
> ```

This line (the basicConfig one) is unnecessary.
___
*[saltapi/graphql/scalars.py, line 9 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVMlY-6kY2WGVnQXIg:-MOVMlY0A7UQJE5mERj1:b-nfn72g) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/graphql/scalars.py#L9)):*
> ```Python
> 
> logger = logging.getLogger(__name__)
> logging.basicConfig(format="%(asctime)s [%(levelname)s]:[%(filename)s, line %(lineno)d]. %(message)s.",
> ```

Calling basicConfig again (without force=True) does nothing. You should call it once, at the very beginning of your app.
___
*[saltapi/graphql/scalars.py, line 21 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVMr4g3RYNy9TA8g6-:-MOVMr4g3RYNy9TA8g60:bngu45l) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/graphql/scalars.py#L21)):*
> ```Python
>     """Parse a proposal code value."""
>     if not proposal_code.startswith("2"):
>         logging.basicConfig(level=logging.INFO)
> ```

This line (the basicConfig one) is unnecessary.
___
*[saltapi/repository/logging_errors.py, line 1 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVN2lm7T8iOYrYEdlm:-MOVN2lm7T8iOYrYEdln:b-hn4p1a) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/repository/logging_errors.py#L1)):*
> ```Python
> import logging
> ```

I guess this file is unnecessary now?
___
*[saltapi/repository/submission_repository.py, line 14 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVNBqB99zfiKit2f8-:-MOVNBqB99zfiKit2f80:b-nfn72g) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/repository/submission_repository.py#L14)):*
> ```Python
> logger = logging.getLogger(__name__)
> logging.basicConfig(format="%(asctime)s [%(levelname)s]:[%(filename)s, line %(lineno)d]. %(message)s.",
>                     datefmt='%Y/%m/%d %H:%M:%S')
> ```

Calling basicConfig again (without force=True) does nothing. You should call it once, at the very beginning of your app.
___
*[saltapi/repository/user_repository.py, line 12 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVNKUX4tm8ZCYNKlNv:-MOVNKUX4tm8ZCYNKlNw:b-nfn72g) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/repository/user_repository.py#L12)):*
> ```Python
> logger = logging.getLogger(__name__)
> logging.basicConfig(format="%(asctime)s [%(levelname)s]:[%(filename)s, line %(lineno)d]. %(message)s.",
>                     datefmt='%Y/%m/%d %H:%M:%S')
> ```

Calling basicConfig again (without force=True) does nothing. You should call it once, at the very beginning of your app.
___
*[saltapi/submission/submit.py, line 14 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVNR229mWZsGhIbUS1:-MOVNR229mWZsGhIbUS2:b-nfn72g) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/submission/submit.py#L14)):*
> ```Python
> logger = logging.getLogger(__name__)
> logging.basicConfig(format="%(asctime)s [%(levelname)s]:[%(filename)s, line %(lineno)d]. %(message)s.",
>                     datefmt='%Y/%m/%d %H:%M:%S')
> ```

Calling basicConfig again (without force=True) does nothing. You should call it once, at the very beginning of your app.
___
*[saltapi/submission/submit.py, line 61 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVOGwZ3gNWUCwiHB21:-MOVOGwZ3gNWUCwiHB22:b-anpuah) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/submission/submit.py#L61)):*
> ```Python
>         raise Exception(error)
>     else:
>         logger.error(msg=error)
> ```

Should be `msg=generic_error`.


<!-- Sent from Reviewable.io -->

2021-01-15 14:32 UTC, Lonwabo11 reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/19)* status: 0 of 8 files reviewed, 17 unresolved discussions (waiting on @hettlage)

___
*[saltapi/auth/authorization.py, line 19 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVAzuQ73BQaw58zSQ0:-MOWNgZZ-qfIlxlBvS6j:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/auth/authorization.py#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Calling basicConfig again (without force=True) does nothing. You should call it once, at the very beginning of your app.
</blockquote></details>

Done.
___
*[saltapi/auth/authorization.py, line 93 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVCAx6Cxi-_JylodyE:-MOWOFUY-cpcY_QEKojZ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/auth/authorization.py#L93)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This line (the basicConfig one) is unnecessary.
</blockquote></details>

Done.
___
*[saltapi/auth/token.py, line 14 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVCpetAJZsTwGd7p9E:-MR5RpfI5UIjDu9symlJ:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/auth/token.py#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Calling basicConfig again (without force=True) does nothing. You should call it once, at the very beginning of your app.
</blockquote></details>

Done.
___
*[saltapi/auth/token.py, line 71 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVD0go0IyBYtIThLv5:-MOWQ0IeDFDiRwa0U0FY:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/auth/token.py#L71)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This line (the basicConfig one) is unnecessary.
</blockquote></details>

Done.
___
*[saltapi/graphql/directives.py, line 43 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVELhD3rqK90zgTvMV:-MOWQ9wj7SbBrCxNQxJv:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/graphql/directives.py#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This line (the basicConfig one) is unnecessary.
</blockquote></details>

Done.
___
*[saltapi/graphql/scalars.py, line 9 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVMlY-6kY2WGVnQXIg:-MR5RvCNDgzpAvLLEdPV:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/graphql/scalars.py#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Calling basicConfig again (without force=True) does nothing. You should call it once, at the very beginning of your app.
</blockquote></details>

Done.
___
*[saltapi/graphql/scalars.py, line 21 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVMr4g3RYNy9TA8g6-:-MR5SHCi3y8fz9FxkKm5:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/graphql/scalars.py#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This line (the basicConfig one) is unnecessary.
</blockquote></details>

Done.
___
*[saltapi/repository/logging_errors.py, line 1 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVN2lm7T8iOYrYEdlm:-MOWQPGM1WPYXqLOmTDg:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/repository/logging_errors.py#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess this file is unnecessary now?
</blockquote></details>

Done.
___
*[saltapi/repository/submission_repository.py, line 14 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVNBqB99zfiKit2f8-:-MR5SKAk1ABXaTI7gStM:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/repository/submission_repository.py#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Calling basicConfig again (without force=True) does nothing. You should call it once, at the very beginning of your app.
</blockquote></details>

Done.
___
*[saltapi/repository/user_repository.py, line 12 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVNKUX4tm8ZCYNKlNv:-MR5SMTm4y1A-YZOtGXH:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/repository/user_repository.py#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Calling basicConfig again (without force=True) does nothing. You should call it once, at the very beginning of your app.
</blockquote></details>

Done.
___
*[saltapi/submission/submit.py, line 14 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVNR229mWZsGhIbUS1:-MR5SO-Z0RTSfSuJ4GO4:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/submission/submit.py#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Calling basicConfig again (without force=True) does nothing. You should call it once, at the very beginning of your app.
</blockquote></details>

Done.
___
*[saltapi/submission/submit.py, line 61 at r2](https://reviewable.io/reviews/saltastroops/salt-api/19#-MOVOGwZ3gNWUCwiHB21:-MOWQokY3qu7hgnr0gHB:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/398b48c7dd8ab99555061bf1014232d0f4aaeac7/saltapi/submission/submit.py#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be `msg=generic_error`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 15:27 UTC, hettlage requested changes
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/19)* status: all files reviewed, 1 unresolved discussion (waiting on @Lonwabo11)

___
*[saltapi/graphql/directives.py, line 17 at r3](https://reviewable.io/reviews/saltastroops/salt-api/19#-MR5dji51fm8VE42BJlS:-MR5dji654Gn9Igsbl4y:b-dpcvg) ([raw file](https://github.com/saltastroops/salt-api/blob/bfb0d817cbf82d73ebea4a556f3b6d671e5a12ba/saltapi/graphql/directives.py#L17)):*
> ```Python
> 
> logger = logging.getLogger(__name__)
> # logging.basicConfig(format="%(asctime)s [%(levelname)s]:[%(filename)s, line %(lineno)d]. %(message)s.",
> ```

These lines should not be commented out but rather be removed.


<!-- Sent from Reviewable.io -->

2021-01-17 17:46 UTC, Lonwabo11 reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/19)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[saltapi/graphql/directives.py, line 17 at r3](https://reviewable.io/reviews/saltastroops/salt-api/19#-MR5dji51fm8VE42BJlS:-MRGS7xn9TEmD58aMr-3:b-896fix) ([raw file](https://github.com/saltastroops/salt-api/blob/bfb0d817cbf82d73ebea4a556f3b6d671e5a12ba/saltapi/graphql/directives.py#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

These lines should not be commented out but rather be removed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-17 19:34 UTC, hettlage approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/salt-api/19)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-17 19:34 UTC, merged